# name of device 
name: se3

# index of output
output_device: 0

# index of input
input_device: 0

# name of the pair
pair_name: se4

# number of devices in the conversation group
group_count: 2

send_order: 0

# number of messages this pair will send back and forth
exchange_count: 100

# protocol
protocol: 4

# volume
volume: 30

# GPT-3 model used
modelA: davinci:ft-parsons-school-of-design-2023-03-03-01-43-18
# modelB: davinci:ft-parsons-school-of-design-2023-03-03-01-43-18
modelB: text-davinci-003

model: text-davinci-003

# negative values lower pitch, positive values increase it
pitch: 15

# can be send or receive
mode: send

# the question to start with if we're in send mode
start_question: "who is a human?"

# question to ask in the case of a timeout
timeout_response: "what does a multispecies constitution mean for humans?"
