# name of device 
name: se2

# index of output
output_device: 0

# index of input
input_device: 1

# name of the pair
pair_name: se1

# number of devices in the conversation group
group_count: 3

# number of messages this pair will send back and forth
exchange_count: 200

# protocol
protocol: 1

# volume
volume: 30

# GPT-3 model used
model: text-davinci-003

# negative values lower pitch, positive values increase it
pitch: 20

# can be send or receive
mode: receive

# the contectual information to accompany text prompt send to GPT-3
pre_prompt: "Ask a question from the perspective of a crop on a farm: "

start_question: "who is a human?"

timeout_response: "what does a multispecies constitution mean for humans?"
