# name of device 
name: se3

# index of output
output_device: 0

# index of input
input_device: 1

# name of the pair
pair_name: se1

# number of messages this pair will send back and forth
exchange_count: 200

# protocol
# 0 - slow audible
# 1 - fast 
# 2 - fastest
# 4 - fast ultrasonic
protocol: 4

# volume
volume: 30

# GPT-3 model used
# model: text-davinci-003
model: davinci:ft-parsons-school-of-design-2023-03-13-10-39-27

# negative values lower pitch, positive values increase it
pitch: -5

# can be send or receive
mode: receive

# question this plant will ask at the beginning
start_question: "who is a human?"

# question to respond to if there's a timeout
timeout_response: "what does a multispecies constitution mean for humans?"
