# name of device 
name: se4

# index of output
output_device: 0

# index of input
input_device: 1

# name of the pair
pair_name: se5

# number of messages this pair will send back and forth
exchange_count: 200

# protocol
protocol: 4

# volume
volume: 30

# GPT-3 model used
# model: davinci:ft-parsons-school-of-design-2023-03-03-01-43-18
model: text-davinci-003

# negative values lower pitch, positive values increase it
pitch: 15

# can be send or receive
mode: send

# the contectual information to accompany text prompt send to GPT-3
pre_prompt: "ask a question about this statement from the perspective of a house plant: "
